name: simple_dart_multilang_select_field
description: Multilang Select Field Component
version: 0.0.2
repository: https://github.com/simple-dart/multilang_select_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_multilang_controller: ^0.0.2
  simple_dart_select_field: ^0.0.2
  simple_dart_ui_core: ^0.0.2

